<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Karyawan extends CI_Controller
{

    function __construct()
    {

        parent::__construct();
        if (!$this->ion_auth->logged_in()){
  			redirect('auth');
  		}
        $this->load->model('Karyawan_model');
        $this->load->library('form_validation','ion_auth');
        $this->load->helper('url');
        $this->user = $this->ion_auth->user()->row();

    }

    public function messageAlert($type, $title) {
      $messageAlert = "
      const Toast = Swal.mixin({
          toast: true,
          position: 'top-end',
          showConfirmButton: false,
          timer: 5000
      });

      Toast.fire({
          type: '".$type."',
          title: '".$title."'
      });
      ";
      return $messageAlert;
  }

    public function index()
    {
        $user = $this->user;
        $karyawan = $this->Karyawan_model->get_all();
        $data = array(
            'karyawan_data' => $karyawan,
            'user' => $user,'users' 	=> $this->ion_auth->user()->row(),

        );

        $this->template->load('template','karyawan_list', $data);
    }


    public function create() {
      $user = $this->user;
        $data = array(
            'button' => 'Create',
            'action' => site_url('karyawan/create_action'),
            'id' => set_value('id'),
      	    'id_karyawan' => set_value('id_karyawan'),
      	    'nama_karyawan' => set_value('nama_karyawan'),
            'user' => $user,'users' 	=> $this->ion_auth->user()->row(),
	       );
        $this->template->load('template','karyawan_form', $data);
    }

    public function create_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
            'id_karyawan' => $this->input->post('id_karyawan',TRUE),
        		'nama_karyawan' => $this->input->post('nama_karyawan',TRUE),
	         );
          $this->Karyawan_model->insert($data);
          $this->session->set_flashdata('messageAlert', $this->messageAlert('success', 'Berhasil menambahkan karyawan'));
          redirect(site_url('karyawan'));
        }
    }

    public function update($id)
    {
      $user = $this->user;
        $row = $this->Karyawan_model->get_by_id($id);
        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('karyawan/update_action'),
                'id' => set_value('id', $row->id),
            		'id_karyawan' => set_value('id_karyawan', $row->id_karyawan),
            		'nama_karyawan' => set_value('nama_karyawan', $row->nama_karyawan),
                'user' => $user,
                'users' 	=> $this->ion_auth->user()->row(),
	             );
            $this->template->load('template','karyawan_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('karyawan'));
        }
    }

    public function update_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_karyawan', TRUE));
        } else {
            $data = array(
            'id_karyawan' => $this->input->post('id_karyawan',TRUE),
        		'nama_karyawan' => $this->input->post('nama_karyawan',TRUE),
	    );

            $this->Karyawan_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('messageAlert', $this->messageAlert('success', 'Berhasil merubah data karyawan'));
            redirect(site_url('karyawan'));
        }
    }

    public function delete($id)
    {
        $row = $this->Karyawan_model->get_by_id($id);

        if ($row) {
            $this->Karyawan_model->delete($id);
          $this->session->set_flashdata('messageAlert', $this->messageAlert('success', 'Berhasil menghapus data karyawan'));
            redirect(site_url('karyawan'));
        } else {
            $this->session->set_flashdata('messageAlert', $this->messageAlert('danger', 'data tidak ditemukan'));
            redirect(site_url('karyawan'));
        }
    }

      public function _rules()
      {
      	$this->form_validation->set_rules('id_karyawan', 'id karyawan', 'trim|required');
        $this->form_validation->set_rules('nama_karyawan', 'nama karyawan', 'trim|required');
      	$this->form_validation->set_rules('id', 'id', 'trim');
      	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
      }



}

/* End of file Karyawan.php */
/* Location: ./application/controllers/Karyawan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-03-18 03:21:05 */
/* http://harviacode.com */
